### ISSUE TITLE
The normalized name of your team is data-analytics

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/da-global-demand-sheets-updater#2]
https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/8cef4ce2a0ae2c716f4aa235fa1928cdaa1a587a/serverless.yml#L20

https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/8cef4ce2a0ae2c716f4aa235fa1928cdaa1a587a/serverless.yml#L26

Replace **DataAnalyst** by **data-analytics**

**Comment by MoralesJonathan** [comment]
Fixed in 7a80db1be669fcba3ac849a0e00064d283d52307
