### ISSUE TITLE
Move your dependencies to dev dependencies and use the existing layers

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/da-global-demand-sheets-updater#4]
The following dependencies are available for you to use as lambda layers.
You don't need to pack them together to deploy
Move them to devDependencies and use the layers

https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/8cef4ce2a0ae2c716f4aa235fa1928cdaa1a587a/package.json#L19
```json
    "@everymundo/simple-logr": "^2.2.4",
    "googleapis": "^39.2.0",
    "pg": "^8.0.2"
  }
```
Right after the following line
https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/8cef4ce2a0ae2c716f4aa235fa1928cdaa1a587a/serverless.yml#L43
you will add

```yaml
    layers:
      - ${cf:node-everymundo-packages-layer.LibLambdaLayerQualifiedArn}
      - ${cf:node-googleapis-39-layer.LibLambdaLayerQualifiedArn}
      - ${cf:node-pg-layer.LibLambdaLayerQualifiedArn}
```

**Comment by MoralesJonathan** [comment]
Fixed in commit 735a8d5ad93031f673e2264e6d3bf7763ac54229
