### ISSUE TITLE
30 seconds timeout

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/da-global-demand-sheets-updater#5]
https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/d1418a90a1a7ae1b9d52eb49b92a461857eee3ec/serverless.yml#L16

@MoralesJonathan, I noticed that currently there is a timeout of 30 for this function
And I also noticed that the code runs the following query in Redshift:
```sql
SELECT * FROM custom.vw_global_demand
```
Do you think that 30 is always going to be enough to run that query?

**Comment by MoralesJonathan** [comment]
Hi @danielsan , you're correct. The query takes anywhere from 6 to 12 minutes to run.
I've increased the timeout to the max allowed time of 15 mins. Please see 925ef9192ec05db370305716f492cace69f97720
